name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
      - name: Ruff check
        run: |
          ruff check .
      - name: Ruff format diff
        run: |
          ruff format --check .
      - name: Black check
        run: |
          black --check --diff .

